In [1]:
import numpy as np


In [2]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[27,  0],
       [77, 46],
       [58, 69],
       [25, 50],
       [85,  1],
       [18, 42],
       [67, 58],
       [41, 22],
       [78, 30],
       [42, 82]])

In [6]:
scalar_model = MinMaxScaler()

In [8]:
type(scalar_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scalar_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
scalar_model.transform(data)

array([[0.13432836, 0.        ],
       [0.88059701, 0.56097561],
       [0.59701493, 0.84146341],
       [0.10447761, 0.6097561 ],
       [1.        , 0.01219512],
       [0.        , 0.51219512],
       [0.73134328, 0.70731707],
       [0.34328358, 0.26829268],
       [0.89552239, 0.36585366],
       [0.35820896, 1.        ]])

In [12]:
scalar_model.fit_transform(data)

array([[0.13432836, 0.        ],
       [0.88059701, 0.56097561],
       [0.59701493, 0.84146341],
       [0.10447761, 0.6097561 ],
       [1.        , 0.01219512],
       [0.        , 0.51219512],
       [0.73134328, 0.70731707],
       [0.34328358, 0.26829268],
       [0.89552239, 0.36585366],
       [0.35820896, 1.        ]])

In [14]:
import pandas as pd

In [15]:
my_data = np.random.randint(0,101,(50,4))

In [16]:
my_data

array([[ 77,  25,  81,  26],
       [ 27,  13,  98,  45],
       [ 45,  72,   3,  76],
       [ 67,  27,  76,   5],
       [ 80,  11,  89,  44],
       [ 25,   3,  91,  14],
       [ 14,  50,  62,  58],
       [  1,  55,  40,  87],
       [ 40,  51,  97,  83],
       [ 63,  79,  11,  32],
       [ 79,  56,  25,   4],
       [ 70,  50,  83,  38],
       [ 41,   3,  86,  75],
       [100,  51,  60,  30],
       [ 10,  94,  41,  50],
       [ 73,  70,  23,  57],
       [  2,  68,  37,  49],
       [ 18,  68,  37,  38],
       [ 41,  28,   5,   6],
       [ 31,  88,  32,  88],
       [ 74,  61,   4,  19],
       [  7,  53,  71,  81],
       [ 40,  46,  86, 100],
       [  7,  80,  97,  24],
       [ 73,  27,   7,  16],
       [ 17,  19,   8,  60],
       [ 64,  67,  61,  19],
       [ 27,   7,  46,  82],
       [ 34, 100,  53,  79],
       [ 77,  31,  41,   9],
       [ 14,  88,  29,  21],
       [ 89,  81,  70,  71],
       [ 11,  35,  37,  73],
       [ 23,  88,  52,  58],
       [ 26,  

In [17]:
import pandas as pd

In [20]:
df = pd.DataFrame(my_data)

In [21]:
df

0    1   2    3
0    77   25  81   26
1    27   13  98   45
2    45   72   3   76
3    67   27  76    5
4    80   11  89   44
5    25    3  91   14
6    14   50  62   58
7     1   55  40   87
8    40   51  97   83
9    63   79  11   32
10   79   56  25    4
11   70   50  83   38
12   41    3  86   75
13  100   51  60   30
14   10   94  41   50
15   73   70  23   57
16    2   68  37   49
17   18   68  37   38
18   41   28   5    6
19   31   88  32   88
20   74   61   4   19
21    7   53  71   81
22   40   46  86  100
23    7   80  97   24
24   73   27   7   16
25   17   19   8   60
26   64   67  61   19
27   27    7  46   82
28   34  100  53   79
29   77   31  41    9
30   14   88  29   21
31   89   81  70   71
32   11   35  37   73
33   23   88  52   58
34   26   41  60    2
35   98   98  61   43
36   56   88  48   28
37   65   31  68   69
38   45    1   2   25
39   38   85   1   36
40   59   49  95   73
41   22    8  19   69
42   18   71  98   22
43   29   18   3   84
44   12   47  12   60
45   17   10  81   60
46   83   29  82    0
47   47   39  32   69
48   48   87  32   83
49   51   40  65   71

In [23]:
df = pd.DataFrame(data = my_data,columns= ['f1','f2','f3','labels'])

In [24]:
df

f1   f2  f3  labels
0    77   25  81      26
1    27   13  98      45
2    45   72   3      76
3    67   27  76       5
4    80   11  89      44
5    25    3  91      14
6    14   50  62      58
7     1   55  40      87
8    40   51  97      83
9    63   79  11      32
10   79   56  25       4
11   70   50  83      38
12   41    3  86      75
13  100   51  60      30
14   10   94  41      50
15   73   70  23      57
16    2   68  37      49
17   18   68  37      38
18   41   28   5       6
19   31   88  32      88
20   74   61   4      19
21    7   53  71      81
22   40   46  86     100
23    7   80  97      24
24   73   27   7      16
25   17   19   8      60
26   64   67  61      19
27   27    7  46      82
28   34  100  53      79
29   77   31  41       9
30   14   88  29      21
31   89   81  70      71
32   11   35  37      73
33   23   88  52      58
34   26   41  60       2
35   98   98  61      43
36   56   88  48      28
37   65   31  68      69
38   45    1   2      25
39   38   85   1      36
40   59   49  95      73
41   22    8  19      69
42   18   71  98      22
43   29   18   3      84
44   12   47  12      60
45   17   10  81      60
46   83   29  82       0
47   47   39  32      69
48   48   87  32      83
49   51   40  65      71

In [25]:
X = df[['f1','f2','f3']]

In [31]:
y = df['labels']

In [27]:
X

f1   f2  f3
0    77   25  81
1    27   13  98
2    45   72   3
3    67   27  76
4    80   11  89
5    25    3  91
6    14   50  62
7     1   55  40
8    40   51  97
9    63   79  11
10   79   56  25
11   70   50  83
12   41    3  86
13  100   51  60
14   10   94  41
15   73   70  23
16    2   68  37
17   18   68  37
18   41   28   5
19   31   88  32
20   74   61   4
21    7   53  71
22   40   46  86
23    7   80  97
24   73   27   7
25   17   19   8
26   64   67  61
27   27    7  46
28   34  100  53
29   77   31  41
30   14   88  29
31   89   81  70
32   11   35  37
33   23   88  52
34   26   41  60
35   98   98  61
36   56   88  48
37   65   31  68
38   45    1   2
39   38   85   1
40   59   49  95
41   22    8  19
42   18   71  98
43   29   18   3
44   12   47  12
45   17   10  81
46   83   29  82
47   47   39  32
48   48   87  32
49   51   40  65

In [33]:
y

0      26
1      45
2      76
3       5
4      44
5      14
6      58
7      87
8      83
9      32
10      4
11     38
12     75
13     30
14     50
15     57
16     49
17     38
18      6
19     88
20     19
21     81
22    100
23     24
24     16
25     60
26     19
27     82
28     79
29      9
30     21
31     71
32     73
33     58
34      2
35     43
36     28
37     69
38     25
39     36
40     73
41     69
42     22
43     84
44     60
45     60
46      0
47     69
48     83
49     71
Name: labels, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [38]:
X_train.shape

(33, 3)

In [41]:
X_test.shape

(17, 3)